// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYddVfTGmRE9_HF6ASdl07Qt7_UEgHiT8',
    appId: '1:547845405757:web:b8714aa97410c154233e54',
    messagingSenderId: '547845405757',
    projectId: 'demoapp-295814',
    authDomain: 'demoapp-295814.firebaseapp.com',
    storageBucket: 'demoapp-295814.appspot.com',
    measurementId: 'G-3Y2WPK8VZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2Vh5DVE0CbSnInnZYb0k_xBhPYdmCNs',
    appId: '1:547845405757:android:c8ee88cb5019aa79233e54',
    messagingSenderId: '547845405757',
    projectId: 'demoapp-295814',
    storageBucket: 'demoapp-295814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Z8V9jX3JRB2PyiRtnP3fSEviMw9iC0w',
    appId: '1:547845405757:ios:7185ab7e93995a23233e54',
    messagingSenderId: '547845405757',
    projectId: 'demoapp-295814',
    storageBucket: 'demoapp-295814.appspot.com',
    iosClientId: '547845405757-olekgnoa5l4441elo8bg0svf0urhpkis.apps.googleusercontent.com',
    iosBundleId: 'com.michelleRaouf.meWeather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Z8V9jX3JRB2PyiRtnP3fSEviMw9iC0w',
    appId: '1:547845405757:ios:7185ab7e93995a23233e54',
    messagingSenderId: '547845405757',
    projectId: 'demoapp-295814',
    storageBucket: 'demoapp-295814.appspot.com',
    iosClientId: '547845405757-olekgnoa5l4441elo8bg0svf0urhpkis.apps.googleusercontent.com',
    iosBundleId: 'com.michelleRaouf.meWeather',
  );
}
